<a href="https://colab.research.google.com/github/colinchu1/CAP4630/blob/master/HW4/HW4(problem2).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Using only numpy, implement the function maxpooling2d. It takes as input input_mat and s and outputs output_mat. The variables input_mat and output_mat are square matrices and s is an integer. It should compute the maxpooling operation on input_mat using window of shape s times s.



#import numpy

In [0]:
import numpy as np

In [0]:
def maxpooling2d(image, s):
    h_prev, w_prev = image.shape
    f = s
    h_prev += h_prev % s
    w_prev += w_prev % s
    downsampled = []
    #return empty matrix if operation can not perform
    if(image.shape[0]< s):
      print("error, operation can not be performed")
      return downsampled
    # calculate output dimensions after the maxpooling operation.
    h = int((h_prev - f)/s)+1
    w = int((w_prev - f)/s)+1
    # create a matrix to hold the values of the maxpooling operation.
    downsampled = np.zeros((h, w)) 
    curr_y = out_y = 0
    # slide the max pooling window vertically across the image
    while curr_y + f <= h_prev:
        curr_x = out_x = 0
        # slide the max pooling window horizontally across the image
        while curr_x + f <= w_prev:
            # choose the maximum value within the window at each step and store it to the output matrix
            downsampled[out_y, out_x] = np.max(image[curr_y:curr_y+f, curr_x:curr_x+f])
            curr_x += s
            out_x += 1
        curr_y += s
        out_y += 1
    return downsampled

#provided testcases

In [3]:

input_mat = []
expected_mat = []
s = []
input_mat.append(np.array([[1, 2, 1, 2],
                      [2, 4, 2, 1],
                      [1, 2, 4, 2],
                      [2, 1, 2, 1]]))
s.append(2)

expected_mat.append(np.array([[4, 2],
                                [2, 4]]))

input_mat.append(np.array([[1, 2, 1, 2, 4, 5],
                      [2, 4, 2, 1, 0, 3],
                      [1, 2, 4, 2, 4, 5],
                      [2, 1, 2, 1, 2, 1],
                      [1, 1, 2, 3, 1, 2]]))
s.append(2)

expected_mat.append([[4, 2, 5],
 [2, 4, 5],
 [1, 3, 2]])


for i in range(len(input_mat)):
  # uncomment top line and comment second line to test code
  output_mat = maxpooling2d(input_mat[i], s[i])

  print(output_mat)

  if np.array_equal(output_mat, expected_mat[i]):
    print("Correct output!")
  else:
    print("Incorrect output!")

[[4. 2.]
 [2. 4.]]
Correct output!
[[4. 2. 5.]
 [2. 4. 5.]
 [1. 3. 2.]]
Correct output!
