<a href="https://colab.research.google.com/github/colinchu1/CAP4630/blob/master/HW4/HW4(problem1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Using only numpy, implement the function conv2d. It takes as input input_mat and kernel_mat and outputs output_mat. All variables are square matrices. It should compute the convolution of input_mat with the kernel kernel_mat using valid padding.

Note that the size s of the kernel matrix can also be an even number.

##import numpy

In [0]:
import numpy as np

In [0]:
def conv2d(input_mat, kernel_mat):
  #if kernel matrix is bigger than input matrix operation can not be perform
  #return empty matrix
  out = []
  if(input_mat.shape[0]<kernel_mat.shape[0]):
    print("error, operation can not be performed")
    return out
  #sub shape will be the size of kernel matrix
  sub_shape = kernel_mat.shape
  view_shape = tuple(np.subtract(input_mat.shape, sub_shape) + 1) + sub_shape
  strides = input_mat.strides + input_mat.strides
  #create all the sub matrix
  sub_matrices = np.lib.stride_tricks.as_strided(input_mat,view_shape,strides)
  #using einsum top find the result matrix
  out = np.einsum('xyij,ij->xy',sub_matrices,kernel_mat)
  
  return out

#Provided test cases

In [3]:
import numpy as np

input_mat = []
kernel_mat = []
expected_mat = []

# test case 1
input_mat.append(np.array([[1, 2, 1, 2],
                      [2, 1, 2, 1],
                      [1, 2, 1, 2],
                      [2, 1, 2, 1]]))

kernel_mat.append(np.array([[1, 0],
                       [0, 1]]))

expected_mat.append(np.array([[2, 4, 2],
                                [4, 2, 4],
                                [2, 4, 2]]))

# test case 2
input_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))
kernel_mat.append(np.array([[1, 0], [0, 1]]))
expected_mat.append(np.array([[2, 0, 0], [0, 2, 0], [0, 0, 2]]))


# test case 3
input_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))
kernel_mat.append(np.array([[1, -1],
                       [-1, 0]]))

expected_mat.append(np.array([[ 1, -1,  0], [-1,  1, -1],[ 0, -1,  1]]))


# test case 4
input_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))
kernel_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))

expected_mat.append(np.array([[4]]))


# test case 5 - should either through an error, or return empty matrix
input_mat.append(np.array([[1, -1],
                       [-1, 0]]))
kernel_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))

expected_mat.append([])



for i in range(len(input_mat)):
  if input_mat[i].shape[0] < kernel_mat[i].shape[0]:
    output_mat = []
  else:
    output_mat = conv2d(input_mat[i], kernel_mat[i])

  print(output_mat)
  if np.array_equal(output_mat, expected_mat[i]):
    print("Correct output!\n")
  else:
    print("Incorrect output!\n")


[[2 4 2]
 [4 2 4]
 [2 4 2]]
Correct output!

[[2 0 0]
 [0 2 0]
 [0 0 2]]
Correct output!

[[ 1 -1  0]
 [-1  1 -1]
 [ 0 -1  1]]
Correct output!

[[4]]
Correct output!

[]
Correct output!

